
services:
  opensearch:
    image: opensearchproject/opensearch:2.12.0
    container_name: opensearch
    environment:
      - cluster.name=learning-opensearch
      - node.name=node-1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms200m -Xmx200m
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=StrongPass@123
      - OPENSEARCH_SECURITY_ENABLED=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.12.0
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=["https://opensearch:9200"]
      - OPENSEARCH_SSL_VERIFICATIONMODE=none
      - OPENSEARCH_USERNAME=kibanaserver
      - OPENSEARCH_PASSWORD=kibanaserver
    ports:
      - "5601:5601"
    depends_on:
      - opensearch


volumes:
  opensearch-data:
